### ISSUE TITLE
Missing plugin.h during compiling.

### ISSUE THREAD

**Issue by yangxuan8282** [raspberrypi-ui/lxplug-ptbatt#1]
hi, I'm trying to compile this plugins on raspberry pi, use this commands:

```
 ./configure --prefix=/usr
```

```
make -j3
```

then got this:

```bash
 make -j3
make  all-recursive
make[1]: Entering directory '/root/src/lxplug-ptbatt/lxplug-ptbatt-master'
Making all in plugins
make[2]: Entering directory '/root/src/lxplug-ptbatt/lxplug-ptbatt-master/plugins'
  CC       ptbatt/ptbatt_la-ptbatt.lo
  CC       ptbatt/ptbatt_la-batt_sys.lo
ptbatt/ptbatt.c:16:10: fatal error: plugin.h: No such file or directory
 #include "plugin.h"
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:514: ptbatt/ptbatt_la-ptbatt.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/root/src/lxplug-ptbatt/lxplug-ptbatt-master/plugins'
make[1]: *** [Makefile:444: all-recursive] Error 1
make[1]: Leaving directory '/root/src/lxplug-ptbatt/lxplug-ptbatt-master'
make: *** [Makefile:376: all] Error 2
[root@1] [~/src/lxplug-ptbatt/lxplug-ptbatt-master] cd plugins/
[root@1] [~/src/lxplug-ptbatt/lxplug-ptbatt-master/plugins] ls
Makefile  Makefile.am  Makefile.in  ptbatt
[root@1] [~/src/lxplug-ptbatt/lxplug-ptbatt-master/plugins] make -j3
  CC       ptbatt/ptbatt_la-ptbatt.lo
ptbatt/ptbatt.c:16:10: fatal error: plugin.h: No such file or directory
 #include "plugin.h"
          ^~~~~~~~~~
compilation terminated.
make: *** [Makefile:514: ptbatt/ptbatt_la-ptbatt.lo] Error 1
```

and got same issues when trying to compile other plugins like lxplug-network

**Comment by spl237** [comment]
You need to install all the dependencies first - apt-get build-dep lxplug-ptbatt. You are missing lxpanel-dev.

**Comment by yangxuan8282** [comment]
@spl237 Thanks for give suggestions. I'm trying to build PIXEL on [pilfs](http://intestinate.com/pilfs/), the sources package of `lxpanel-dev` should be `lxpanel`, but seems there are several repos related to `lxpanel`: `pipanel`, `lxpanel-stretch`, and `lxpanel`, which should I use?

**Comment by spl237** [comment]
pipanel is nothing to do with lxpanel. lxpanel is the jessie version. lxpanel-stretch is the latest version and the one you should use. But I strongly suggest you use the sources from our apt repository rather than taking code from Github, or you will just run into yet more dependency problems.

**Comment by yangxuan8282** [comment]
So if I want to compile `lxpanel` just grab this: http://archive.raspberrypi.org/debian/pool/ui/l/lxpanel/lxpanel_0.9.3.orig.tar.xz ?

**Comment by spl237** [comment]
No, that is just the source code from the original Debian repo; it doesn't include our changes to it.

To be honest, you don't seem to understand a great deal about building Debian packages from source, and this site - which is a bug tracker - is not really the place to learn how to do it. There is a lot of info online about Debian packaging and how to build from it. Can I please suggest you have a look at that, or put a query on our forums and see if someone there can help you with this?

**Comment by yangxuan8282** [comment]
I just realize on debian should use `apt-get source <pkgs>` to get sources. Thanks for your help.
