### ISSUE TITLE
battery status indicator icons

### ISSUE THREAD

**Issue by b1ack0p** [raspberrypi-ui/lxplug-ptbatt#10]
Hi,
may I kindly ask where can I find battery/power status indicator icons used in RaspberryPiOS x86 ? I can't find them in PiXflat icons.

like this:
![Screenshot_2022-05-06_22-35-17](https://user-images.githubusercontent.com/72235930/167205892-900bfcec-f45d-4ac2-9e65-2e7e67051c79.png)

thanks in advance

**Comment by spl237** [comment]
They're not a pre-created icon; they're drawn from scratch with cairo line and fill commands. Look at the function draw_icon in ptbatt.c.

**Comment by b1ack0p** [comment]
thanks for your reply.
i am trying to modify PiXflat theme/icons for Xfce4 on Debian 11 x64 but now only battery icons missing and i am struggling. since there is not battery icons in PiXflat icons Xfce is using stock icons from stock themes such as Adwaita or hicolor and they are ugly. I already renamed wifi/wlan/bluetooth/volume icons for system to pick them, you can see in the screenshot below it looks beautiful now. Unfortunately i had to use another Xfwm4 theme close look to default PiXflat theme even it is not perfect, because PiXflat is not made for Xfce.

is there a way to generate battery icons to .svg file or something?


![Screenshot_2022-05-09_08-49-24](https://user-images.githubusercontent.com/72235930/167348211-7d48cd9b-74ce-478f-b2b2-45d97f214ed2.png)
