### ISSUE TITLE
lxpanel hangs if pi-top device manager stops being available

### ISSUE THREAD

**Issue by m-roberts** [raspberrypi-ui/lxplug-ptbatt#2]
If it is not detected at boot, then this is not an issue. However, if the plugin loses its connection to the device manager, then lxpanel will hang and the user will no longer be able to interact with it.

`sudo systemctl stop pt-device-manager` during a session will replicate this behaviour.

**Comment by spl237** [comment]
Hmmm. It hangs up in the zmq_recv function waiting for a response to the message sent to the device manager. This function nominally blocks waiting for a response, but this is never noticed as it returns very quickly if the manager is running. The function can be run in non-blocking mode, but it then takes around 1000-2000 polls in a loop to return a value.

There are three approaches to this.

  1) Rewrite the code which calls zmq_recv so it gets polled by a timer xxx ms after the zmq send, in the expectation that we can work out an appropriate interval which works for all Pis to ensure that data is received.

  2) Kludge it so we call zmq_recv in a tight loop - as I have done now for a quick and dirty fix to establish that this is actually the problem.

  3) Leave it as is.

 The second option is quick but wrong. The first is the right thing to do, but is a major rewrite of some of the plugin code and may have side effects I haven't considered.

 Leave it as is may be a viable option depending on how often the pt-device-manager dies in normal use - given we have been running this plugin for 6 months, and this issue has only just been raised (and I've never seen it on my piTop) - does this happen often enough to justify the effort to do 1)?

**Comment by spl237** [comment]
I've checked in a fix for this - please download and try it, and let me know if it works for you. It seems to have fixed the problem for me (and it even means the battery indicator carries on working if the device manager magically starts again...)

**Comment by ItsChoudhry** [comment]
Hi I tested the change and the panel doesn't hang after running `sudo systemctl stop pt-device-manager` anymore, but there is a issue with the panel icon in the bottom left which is used to open the menu is gone.

**Comment by ItsChoudhry** [comment]
Hi Simon, I have tested again on a clean image and it works perfectly. It must have been my previous configuration! Thanks for your work on this.
