### ISSUE TITLE
Add support for `pi-topd`

### ISSUE THREAD

**Issue by m-roberts** [raspberrypi-ui/lxplug-ptbatt#9]
`pt-device-manager` is now called [`pi-topd`](https://github.com/pi-top/pi-topd) for Bullseye onwards. System service check should be done for `pi-topd` as well as `pt-device-manager`, to support both service names.

**Comment by spl237** [comment]
https://github.com/raspberrypi-ui/lxplug-ptbatt/commit/cf0b6fc65c5d6e53f542bc9e040e27b0851cc453 should fix this

**Comment by m-roberts** [comment]
Thanks!

**Comment by aivarannamaa** [comment]
@m-roberts, how to install Pi-top support in the new RPi Bullseye? I tried `pitopd` and `pi-topd`

**Comment by m-roberts** [comment]
Using the buster packages (`pt-device-manager`) should work for now. You can follow the `pi-topd` project [here](https://github.com/pi-top/pi-topd) to find out when we have released all of our latest changes!
